### ISSUE TITLE
Take Off Malfunction Suggestion

### ISSUE THREAD

**Issue by PixelatedPulse** [zealsprince/lc-malfunctions#1]
A ship takeoff malfunction so when you hit the leave lever it can require a fix outside the ship forcing one of the crew members to be sent outside to fix it when you're all already trying to leave. MOREOVER, when they complete the outside task just make the ship automatically start taking off instead of just fixing the lever.

**Comment by zealsprince** [comment]
I was thinking of some kind of ship takeoff delay mechanic as well! However, I think making a player leave the ship to go to a specific part of the ship each time might become old and more of a chore than a fun feature. Something to discuss!

I did consider making some kind of take-off delay mechanic as one of the malfunctions. Going over it then though: I think in general when players decide to leave it's more fun to just leave versus adding a roadblock they need to solve or wait on such as take-off being delayed.

Some scenarios I considered for this:
- Players have an eyeless dog in the ship: a delay would be unfair and remove player agency possibly killing the player in the process
- Players want to leave because they're all in the ship and done with collecting scrap: a delay wouldn't add anything and would be more of an annoyance

Going over it now though, if the chance of this happening was tiny (1%), it could be fun and possibly panic inducing for that one time you need it to take off immediately. I'll think about it a little more! I especially like the fact that the ship immediately takes off then.

**Comment by 3e2j** [comment]
To me, the ship malfunctions seem to occur way too often, and sometimes take you to moons that require a decent amount of scrap to get there. I had a malfunction take me to "Secret Labs", which normally costs 600 to fly to. It seems a bit more of an advantage than a disadvantage. One change I _strongly_ recommend is allowing malfunctions to be routing only towards **planets that match or surpass the current quota required**. 

Even still, the malfunctions are designed to be random, rather than a consequence of doing something else.

I feel like that there needs to be a reason for malfunctions.

- The company not paying for repairs as a consequence of penalty fees
- Not charging your ship via the apparatus [should probably be a rare malfunction if implemented this way due to some people having Facility Meltdown installed]
- Not using the radar booster to accurately find and teleport bodies
The ideas are bountiful and could really shake up the gameplay.

Whilst super-rare randomness to the malfunctions are fun, and definitely should stay. There needs to at least be at least some kind of system in place that keeps it in the players control the majority of the time.

This mod is clearly intended to punish the players. But it needs a reason that players can understand, and methods that the player can use to counteract the punishments, perhaps even rewarding them for doing so [apparatus overcharge allowing for higher moon quota jumps without the initial cost]. I reckon that following a design flow like this could give a greater use to some items/scrap that are rarely used, and make them desirable for the risk.

**Comment by Easyidle123** [comment]
I believe in this suggestion. Having the ship rarely be unable to leave could make for some brutal and (in my opinion) more interesting days. Landing in an eclipse, thinking "we'll leave immediately", and then being trapped til 11am would force players to go find a safer area or hunker down inside the ship. 
I hear what you mean about repairs being tedious and about forcing the player to stay being unfun, so I think a solution that fixes both issues is an optional repair / part retrieval that would make the ship launch immediately. Players could either wait until the malfunction is over, or take a risk by leaving the ship and hoping to get it out earlier.

I think ship engine malfunction could be generalized too. Maybe your engines fail in orbit and you're trapped on a moon for the rest of a Quota, or maybe just for the next day.

Landing later in the day could be interesting. I think you can also reverse it to the ship randomly deciding to leave earlier than usual. This could be announced at the start of the day, or have an "alert: the ship is malfunctioning and will leave at ______!" It can be justified as either the ship auto leave goes haywire, or the company wants to get their ship back early before the malfunction prevents the ship from leaving.

**Comment by zealsprince** [comment]
I was reading @3e2j's comment last night and thought about it a bit more. I really like some of the things mentioned in this and I think I'll start implementation of a few of these aspects. Here are some things I really like and who I'm intending to approach them:

> To me, the ship malfunctions seem to occur way too often.

This is an inevitable side-effect of having a truly random system. Me and my friends played with the most recent version of the mod and its default probabilities (Navigation 12.5% / Teleporter 10% / Power 5%) and we never hit a single malfunction after 4 quota weeks. There's just a chance that you'll have bad rolls multiple times. I can reduce the probabilities further since the idea of the mod too was to have malfunctions be a true rarity that catch you off guard. However even in reducing probabilities, it does not rule out having multiple malfunctions in a row like you experienced.

I played with the idea of a weighted system where the chance of a malfunction happening increases over time if it's not triggered. To me that felt too gamified though for the scenarios that are in place. You can essentially count the system knowing that you're going to experience a malfunction the next day if you haven't had one in 8 days. With a random system this is not the case.

> One change I strongly recommend is allowing malfunctions to be routing only towards planets that match or surpass the current quota required [...] This mod is clearly intended to punish the players.

I will add a config toggle for this as I would personally not play with it but I absolutely understand the use. You're right that malfunctions should mostly punish players. The navigation one is a bit of an oddball and the reason I started this mod though. I found me and my friends weren't going to some moons as much as I would have liked and that gameplay became a bit stale. Yes, the navigation malfunction can take you to an expensive moon like Titan at no cost with no weather making it easier. The point there was still that it's an inconvenience in some way but there's also the upside that you can then stay after, if you wish. The weather can still be bad afterwards so you have to make a choice of staying at a high yield moon or abandoning it for something safer. This is already a decision that needs to be made by players when they pay for a route so I think this adds to it.

> I feel like that there needs to be a reason for malfunctions: The company not paying for repairs as a consequence of penalty fees

This one I quite like. Having some probability increase would be fun if tied to something like the recovery penalty which can be easily avoided. I will have to think if this is going to be a single configuration value or if it's by malfunction. Additionally I need to figure out if it's a flat value or multiplied by players not recovered.

____

I like a lot of the suggestions you're making @Easyidle123. There's definitely additional navigation/engine scenarios that could be interesting and fun that expand the game loop.

> [...] I think you can also reverse it to the ship randomly deciding to leave earlier than usual. This could be announced at the start of the day, or have an "alert: the ship is malfunctioning and will leave at ______!" It can be justified as either the ship auto leave goes haywire, or the company wants to get their ship back early before the malfunction prevents the ship from leaving.

My only concern with the ship leaving early is that it can force players into unwinnable scenarios that could be run-enders. Take for instance being on your last day of quota, you just lost all your scrap the day before. Not only that but your crew was not recovered leading to an increase in malfunctions as per @3e2j's suggestions. Now you're on your last haul trying to just meet quota and the ship says it's leaving 6 hours earlier than usual. I think this would be negative feedback loop that could be more frustrating than rewarding.

Maybe the take-off delay (Engine?) malfunction is not impacted by the probability increase but it's still something to think about. I'll see what I can do with these suggestions though!

**Comment by zealsprince** [comment]
@3e2j it's going to be a bit more difficult to implement the quota cost limit functionality. I think I'll have to use LethalLib to make my life easier or just skip this feature for now. I've tweaked probabilities and added the penalty mechanic in the latest version.

Additionally there are two new malfunctions. One is a new door specific malfunction that essentially replicates what @Easyidle123 mentioned in not being able to take off.

Keep in mind no matter how this is implemented I don't think we should overwrite the voting mechanic. This means that dead players can still cause the ship to take off.

My spin with the doors remaining locked until late is to possibly capture a player inside the ship who is on coms having to teleport people in or teleport themselves out if they are locked. Additionally they can coordinate with players outside to launch the ship if players boarded or on the roof. I felt this gave a good balance to forcing people outside the safety of the ship itself while not introducing a whole new mechanic that deviates from the base game.

In case all players are locked out we essentially have the "blocked take-off" as a feature.

There's still a "grace period" so to speak where the doors open if they were locked. This is displayed on the door controls inside as well and happens at 10pm when the autopilot advises players to return to the ship. I think at this point the game outside is already difficult enough and gives players ample time to get back inside if they haven't found a way already.
